---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "text-embedder.fullname" . }}
  labels: {{- include "text-embedder.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.http_port }}
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      {{- with .Values.service.nodePort }}
      nodePort:  {{ . }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.grpc_port }}
    - port: {{ .Values.service.grpc_port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: 8002
      targetPort: metrics
      name: metrics
    {{- end }}

  selector:
    {{- include "text-embedder.selectorLabels" . | nindent 4 }}
